// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 30/8/2024, 4:01:45 p.m.
const configMerger = require("C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/plugins/**/*.{js,ts,mjs}","C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/composables/**/*.{js,ts,mjs}","C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/utils/**/*.{js,ts,mjs}","C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["11"] = "C:/Users/Javi/Documents/workspace/nuxtjs/blog-nuxt3/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
